Create directorytree.txt
mr-mdd/CSCK541---EOM---Group-A pull request #2
Opened 2023-09-26 21:32 UTC by jdj1907

2023-09-29 16:07 UTC, miguelvaladas requested changes
Hi, can you change the file name to snake_case which is the convention for Python even though this is a txt file? like directory_tree.txt? It would be more readable across the project. Can you also include it in a docs/ folder inside the project?

2023-10-03 15:46 UTC, mr-mdd approved these changes
Approved per our reviews. Thanks Miguel!

2023-10-05 10:40 UTC, miguelvaladas approved these changes

2023-10-05 10:40 UTC, kwansinnn approved these changes

2023-10-05 10:40 UTC, merged